# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MLKitTestApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MLKitTestApp
  pod 'GoogleMLKit/DigitalInkRecognition', '2.4.0'

  target 'MLKitTestAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MLKitTestAppUITests' do
    # Pods for testing
  end

end
